version: '3.3'

services:
  discoveryserver:
    container_name: discoveryserver
    restart: always
    image: anavarrooo/resultadosmaster:discoveryserver
    ports:
      - 8761:8761
    networks:
      - resultadosmasternt
    environment:
      eureka.instance.hostname: discoveryserver
      eureka.client.serviceUrl.defaultZone: http://discoveryserver:8761/eureka

  api-gateway:
    container_name: api-gateway
    image: anavarrooo/resultadosmaster:api-gateway
    ports:
      - 8084:8084
    depends_on:
      - discoveryserver
    networks:
      - resultadosmasternt

  register-service:
    container_name: register-service
    image: anavarrooo/resultadosmaster:register-service
    ports:
      - 8083:8083
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:mysql://resultadosmaster-mysql-server.mysql.database.azure.com:3306/usuarios?useSSL=false
      - DATABASE_USERNAME=resultadosmaster
      - DATABASE_PASSWORD=Tolito1234
    networks:
      - resultadosmasternt

  ranking-service:
    container_name: ranking-service
    image: anavarrooo/resultadosmaster:ranking-service
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:mysql://resultadosmaster-mysql-server.mysql.database.azure.com:3306/top50players?autoReconnect=true&useSSL=false
      - DATABASE_USERNAME=resultadosmaster
      - DATABASE_PASSWORD=Tolito1234
    networks:
      - resultadosmasternt

  resultados-service:
    container_name: resultados-service
    image: anavarrooo/resultadosmaster:resultados-service
    ports:
      - 8082:8082
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:mysql://resultadosmaster-mysql-server.mysql.database.azure.com:3306/resultadosmaster?autoReconnect=true&useSSL=false
      - DATABASE_USERNAME=resultadosmaster
      - DATABASE_PASSWORD=Tolito1234
    networks:
      - resultadosmasternt

networks:
  resultadosmasternt:
    driver: bridge