spring:
  cloud:
    gateway:
      routes:
        - id: ranking-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/ranking/**
          filters:
            - name: AuthenticationFilter

        - id: resultados-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/partidos/**
          filters:
            - name: AuthenticationFilter

        - id: resultados-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/torneos/**
          filters:
            - name: AuthenticationFilter

        - id: register-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**



