spring:
  cloud:
    gateway:
      routes:
        - id: ranking-service
          uri: lb://ranking-service
          predicates:
            - Path=/api/v1/ranking/**
          filters:
            - name: AuthenticationFilter

        - id: resultados-service
          uri: lb://resultados-service
          predicates:
            - Path=/api/v1/partidos/**
          filters:
            - name: AuthenticationFilter

        - id: resultados-service
          uri: lb://resultados-service
          predicates:
            - Path=/api/v1/torneos/**
          filters:
            - name: AuthenticationFilter

        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/



