spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ranking-service
          uri: lb://ranking-service:8081
          predicates:
            - Path=/api/v1/ranking/**
          filters:
            - name: AuthenticationFilter

        - id: resultados-service
          uri: lb://resultados-service:8082
          predicates:
            - Path=/api/v1/partidos/**
          filters:
            - name: AuthenticationFilter

        - id: resultados-service
          uri: lb://resultados-service:8082
          predicates:
            - Path=/api/v1/torneos/**
          filters:
            - name: AuthenticationFilter

        - id: register-service
          uri: lb://register-service:8083
          predicates:
            - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryserver:8761/eureka/

server:
  port: 8084

jpa:
  properties:
    hibernate:
      jdbc:
        time_zone: Europe/Madrid

management:
  endpoints:
    web:
      exposure:
        include: "*"
